/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as AdminAuthenticatedActivityLogRouteImport } from './routes/admin._authenticated.activity-log'
import { Route as AdminAuthenticatedBlogsRouteImport } from './routes/admin._authenticated.blogs'
import { Route as AdminAuthenticatedCategoriesRouteImport } from './routes/admin._authenticated.categories'
import { Route as AdminAuthenticatedClientsRouteImport } from './routes/admin._authenticated.clients'
import { Route as AdminAuthenticatedDashboardRouteImport } from './routes/admin._authenticated.dashboard'
import { Route as AdminAuthenticatedFaqsRouteImport } from './routes/admin._authenticated.faqs'
import { Route as AdminAuthenticatedGalleryRouteImport } from './routes/admin._authenticated.gallery'
import { Route as AdminAuthenticatedHeroSlidesRouteImport } from './routes/admin._authenticated.hero-slides'
import { Route as AdminAuthenticatedIndustriesRouteImport } from './routes/admin._authenticated.industries'
import { Route as AdminAuthenticatedLeadsRouteImport } from './routes/admin._authenticated.leads'
import { Route as AdminAuthenticatedMediaRouteImport } from './routes/admin._authenticated.media'
import { Route as AdminAuthenticatedPartnersRouteImport } from './routes/admin._authenticated.partners'
import { Route as AdminAuthenticatedPortfolioRouteImport } from './routes/admin._authenticated.portfolio'
import { Route as AdminAuthenticatedPricingRouteImport } from './routes/admin._authenticated.pricing'
import { Route as AdminAuthenticatedProductsRouteImport } from './routes/admin._authenticated.products'
import { Route as AdminAuthenticatedServicesRouteImport } from './routes/admin._authenticated.services'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin._authenticated.settings'
import { Route as AdminAuthenticatedStatisticsRouteImport } from './routes/admin._authenticated.statistics'
import { Route as AdminAuthenticatedTeamRouteImport } from './routes/admin._authenticated.team'
import { Route as AdminAuthenticatedTestimonialsRouteImport } from './routes/admin._authenticated.testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const AdminAuthenticatedActivityLogRoute =
  AdminAuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBlogsRoute = AdminAuthenticatedBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedCategoriesRoute =
  AdminAuthenticatedCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedClientsRoute =
  AdminAuthenticatedClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedDashboardRoute =
  AdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedFaqsRoute = AdminAuthenticatedFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedGalleryRoute =
  AdminAuthenticatedGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedHeroSlidesRoute =
  AdminAuthenticatedHeroSlidesRouteImport.update({
    id: '/hero-slides',
    path: '/hero-slides',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedIndustriesRoute =
  AdminAuthenticatedIndustriesRouteImport.update({
    id: '/industries',
    path: '/industries',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedLeadsRoute = AdminAuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedMediaRoute = AdminAuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedPartnersRoute =
  AdminAuthenticatedPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedPortfolioRoute =
  AdminAuthenticatedPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedPricingRoute =
  AdminAuthenticatedPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedProductsRoute =
  AdminAuthenticatedProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedServicesRoute =
  AdminAuthenticatedServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedStatisticsRoute =
  AdminAuthenticatedStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedTeamRoute = AdminAuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedTestimonialsRoute =
  AdminAuthenticatedTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/activity-log': typeof AdminAuthenticatedActivityLogRoute
  '/admin/blogs': typeof AdminAuthenticatedBlogsRoute
  '/admin/categories': typeof AdminAuthenticatedCategoriesRoute
  '/admin/clients': typeof AdminAuthenticatedClientsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/faqs': typeof AdminAuthenticatedFaqsRoute
  '/admin/gallery': typeof AdminAuthenticatedGalleryRoute
  '/admin/hero-slides': typeof AdminAuthenticatedHeroSlidesRoute
  '/admin/industries': typeof AdminAuthenticatedIndustriesRoute
  '/admin/leads': typeof AdminAuthenticatedLeadsRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/portfolio': typeof AdminAuthenticatedPortfolioRoute
  '/admin/pricing': typeof AdminAuthenticatedPricingRoute
  '/admin/products': typeof AdminAuthenticatedProductsRoute
  '/admin/services': typeof AdminAuthenticatedServicesRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/statistics': typeof AdminAuthenticatedStatisticsRoute
  '/admin/team': typeof AdminAuthenticatedTeamRoute
  '/admin/testimonials': typeof AdminAuthenticatedTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/activity-log': typeof AdminAuthenticatedActivityLogRoute
  '/admin/blogs': typeof AdminAuthenticatedBlogsRoute
  '/admin/categories': typeof AdminAuthenticatedCategoriesRoute
  '/admin/clients': typeof AdminAuthenticatedClientsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/faqs': typeof AdminAuthenticatedFaqsRoute
  '/admin/gallery': typeof AdminAuthenticatedGalleryRoute
  '/admin/hero-slides': typeof AdminAuthenticatedHeroSlidesRoute
  '/admin/industries': typeof AdminAuthenticatedIndustriesRoute
  '/admin/leads': typeof AdminAuthenticatedLeadsRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/portfolio': typeof AdminAuthenticatedPortfolioRoute
  '/admin/pricing': typeof AdminAuthenticatedPricingRoute
  '/admin/products': typeof AdminAuthenticatedProductsRoute
  '/admin/services': typeof AdminAuthenticatedServicesRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/statistics': typeof AdminAuthenticatedStatisticsRoute
  '/admin/team': typeof AdminAuthenticatedTeamRoute
  '/admin/testimonials': typeof AdminAuthenticatedTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_authenticated/activity-log': typeof AdminAuthenticatedActivityLogRoute
  '/admin/_authenticated/blogs': typeof AdminAuthenticatedBlogsRoute
  '/admin/_authenticated/categories': typeof AdminAuthenticatedCategoriesRoute
  '/admin/_authenticated/clients': typeof AdminAuthenticatedClientsRoute
  '/admin/_authenticated/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/_authenticated/faqs': typeof AdminAuthenticatedFaqsRoute
  '/admin/_authenticated/gallery': typeof AdminAuthenticatedGalleryRoute
  '/admin/_authenticated/hero-slides': typeof AdminAuthenticatedHeroSlidesRoute
  '/admin/_authenticated/industries': typeof AdminAuthenticatedIndustriesRoute
  '/admin/_authenticated/leads': typeof AdminAuthenticatedLeadsRoute
  '/admin/_authenticated/media': typeof AdminAuthenticatedMediaRoute
  '/admin/_authenticated/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/_authenticated/portfolio': typeof AdminAuthenticatedPortfolioRoute
  '/admin/_authenticated/pricing': typeof AdminAuthenticatedPricingRoute
  '/admin/_authenticated/products': typeof AdminAuthenticatedProductsRoute
  '/admin/_authenticated/services': typeof AdminAuthenticatedServicesRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/_authenticated/statistics': typeof AdminAuthenticatedStatisticsRoute
  '/admin/_authenticated/team': typeof AdminAuthenticatedTeamRoute
  '/admin/_authenticated/testimonials': typeof AdminAuthenticatedTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/services'
    | '/studio'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/work'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/admin/activity-log'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/hero-slides'
    | '/admin/industries'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/partners'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/statistics'
    | '/admin/team'
    | '/admin/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/services'
    | '/studio'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/work'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/work/$slug'
    | '/admin/activity-log'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/hero-slides'
    | '/admin/industries'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/partners'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/statistics'
    | '/admin/team'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/services'
    | '/studio'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/work'
    | '/admin/_authenticated'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/admin/_authenticated/activity-log'
    | '/admin/_authenticated/blogs'
    | '/admin/_authenticated/categories'
    | '/admin/_authenticated/clients'
    | '/admin/_authenticated/dashboard'
    | '/admin/_authenticated/faqs'
    | '/admin/_authenticated/gallery'
    | '/admin/_authenticated/hero-slides'
    | '/admin/_authenticated/industries'
    | '/admin/_authenticated/leads'
    | '/admin/_authenticated/media'
    | '/admin/_authenticated/partners'
    | '/admin/_authenticated/portfolio'
    | '/admin/_authenticated/pricing'
    | '/admin/_authenticated/products'
    | '/admin/_authenticated/services'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/statistics'
    | '/admin/_authenticated/team'
    | '/admin/_authenticated/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StudioRoute: typeof StudioRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WorkRoute: typeof WorkRouteWithChildren
  IndustriesSlugRoute: typeof IndustriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/admin/_authenticated/activity-log': {
      id: '/admin/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AdminAuthenticatedActivityLogRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/blogs': {
      id: '/admin/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAuthenticatedBlogsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/categories': {
      id: '/admin/_authenticated/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAuthenticatedCategoriesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/clients': {
      id: '/admin/_authenticated/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAuthenticatedClientsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/dashboard': {
      id: '/admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/faqs': {
      id: '/admin/_authenticated/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminAuthenticatedFaqsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/gallery': {
      id: '/admin/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminAuthenticatedGalleryRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/hero-slides': {
      id: '/admin/_authenticated/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AdminAuthenticatedHeroSlidesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/industries': {
      id: '/admin/_authenticated/industries'
      path: '/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AdminAuthenticatedIndustriesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/leads': {
      id: '/admin/_authenticated/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminAuthenticatedLeadsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/media': {
      id: '/admin/_authenticated/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAuthenticatedMediaRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/partners': {
      id: '/admin/_authenticated/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminAuthenticatedPartnersRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/portfolio': {
      id: '/admin/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminAuthenticatedPortfolioRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/pricing': {
      id: '/admin/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminAuthenticatedPricingRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/products': {
      id: '/admin/_authenticated/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAuthenticatedProductsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/services': {
      id: '/admin/_authenticated/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminAuthenticatedServicesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/statistics': {
      id: '/admin/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminAuthenticatedStatisticsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/team': {
      id: '/admin/_authenticated/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAuthenticatedTeamRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/testimonials': {
      id: '/admin/_authenticated/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAuthenticatedTestimonialsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedActivityLogRoute: typeof AdminAuthenticatedActivityLogRoute
  AdminAuthenticatedBlogsRoute: typeof AdminAuthenticatedBlogsRoute
  AdminAuthenticatedCategoriesRoute: typeof AdminAuthenticatedCategoriesRoute
  AdminAuthenticatedClientsRoute: typeof AdminAuthenticatedClientsRoute
  AdminAuthenticatedDashboardRoute: typeof AdminAuthenticatedDashboardRoute
  AdminAuthenticatedFaqsRoute: typeof AdminAuthenticatedFaqsRoute
  AdminAuthenticatedGalleryRoute: typeof AdminAuthenticatedGalleryRoute
  AdminAuthenticatedHeroSlidesRoute: typeof AdminAuthenticatedHeroSlidesRoute
  AdminAuthenticatedIndustriesRoute: typeof AdminAuthenticatedIndustriesRoute
  AdminAuthenticatedLeadsRoute: typeof AdminAuthenticatedLeadsRoute
  AdminAuthenticatedMediaRoute: typeof AdminAuthenticatedMediaRoute
  AdminAuthenticatedPartnersRoute: typeof AdminAuthenticatedPartnersRoute
  AdminAuthenticatedPortfolioRoute: typeof AdminAuthenticatedPortfolioRoute
  AdminAuthenticatedPricingRoute: typeof AdminAuthenticatedPricingRoute
  AdminAuthenticatedProductsRoute: typeof AdminAuthenticatedProductsRoute
  AdminAuthenticatedServicesRoute: typeof AdminAuthenticatedServicesRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRoute
  AdminAuthenticatedStatisticsRoute: typeof AdminAuthenticatedStatisticsRoute
  AdminAuthenticatedTeamRoute: typeof AdminAuthenticatedTeamRoute
  AdminAuthenticatedTestimonialsRoute: typeof AdminAuthenticatedTestimonialsRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedActivityLogRoute: AdminAuthenticatedActivityLogRoute,
  AdminAuthenticatedBlogsRoute: AdminAuthenticatedBlogsRoute,
  AdminAuthenticatedCategoriesRoute: AdminAuthenticatedCategoriesRoute,
  AdminAuthenticatedClientsRoute: AdminAuthenticatedClientsRoute,
  AdminAuthenticatedDashboardRoute: AdminAuthenticatedDashboardRoute,
  AdminAuthenticatedFaqsRoute: AdminAuthenticatedFaqsRoute,
  AdminAuthenticatedGalleryRoute: AdminAuthenticatedGalleryRoute,
  AdminAuthenticatedHeroSlidesRoute: AdminAuthenticatedHeroSlidesRoute,
  AdminAuthenticatedIndustriesRoute: AdminAuthenticatedIndustriesRoute,
  AdminAuthenticatedLeadsRoute: AdminAuthenticatedLeadsRoute,
  AdminAuthenticatedMediaRoute: AdminAuthenticatedMediaRoute,
  AdminAuthenticatedPartnersRoute: AdminAuthenticatedPartnersRoute,
  AdminAuthenticatedPortfolioRoute: AdminAuthenticatedPortfolioRoute,
  AdminAuthenticatedPricingRoute: AdminAuthenticatedPricingRoute,
  AdminAuthenticatedProductsRoute: AdminAuthenticatedProductsRoute,
  AdminAuthenticatedServicesRoute: AdminAuthenticatedServicesRoute,
  AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRoute,
  AdminAuthenticatedStatisticsRoute: AdminAuthenticatedStatisticsRoute,
  AdminAuthenticatedTeamRoute: AdminAuthenticatedTeamRoute,
  AdminAuthenticatedTestimonialsRoute: AdminAuthenticatedTestimonialsRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StudioRoute: StudioRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WorkRoute: WorkRouteWithChildren,
  IndustriesSlugRoute: IndustriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
